pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                script {
                    def uid = sh(script: 'id -u', returnStdout: true).trim()
                    def gid = sh(script: 'id -g', returnStdout: true).trim()

                    dockerImage = docker.build(
                        'asset-tools-env',
                        "--build-arg UID=${uid} --build-arg GID=${gid} ./app"
                    )
                }
            }
        }

        stage('Build App') {
            agent {
                docker {
                    image 'asset-tools-env'
                    reuseNode true
                    args '-v vcpkg-cache:/vcpkg-cache'
                }
            }
            steps {
                sh '''
                    git --version
                    gcc --version
                    cmake --version

                    id
                    pwd
                    ls -lad
                    ls -lad /workspace
                    ls -lad /workspace/vcpkg
                    ls -lad /var/jenkins_home/workspace

                    ./scripts/build.sh

                    ./build/app/AssetTools --version
                '''
            }
        }
        stage("Validate Assets") {
            agent {
                docker {
                    image 'asset-tools-env'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ./build/app/AssetTools validate . --texture-config textures.yaml --audio-config audio.yaml
                '''
            }
        }
    }
}